# Simple workflow for deploying static content to GitHub Pages
name: Compile Latex and Publish to Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_latex_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: main.pdf
      - name: Generate redirect page
        run: |
          mkdir public
          mv main.pdf public/
          cat > public/index.html <<EOL
          <!doctype html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0;url=./main.pdf" />
              <title>Wait for redirect!</title>
            </head>
            <body>
              <p><a href="./main.pdf">You should've been redirected to here</a></p>
            </body>
          </html>
          EOL
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
